# Generated by Django 2.0.8 on 2018-08-07 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Dispose',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('disposed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('iid', models.AutoField(primary_key=True, serialize=False)),
                ('manufacture_name', models.CharField(max_length=20)),
                ('device_type', models.CharField(max_length=20)),
                ('serial_number', models.CharField(max_length=30, unique=True)),
                ('location', models.CharField(max_length=120)),
                ('proprietor', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Active', 'ACTIVE'), ('Inactive', 'INACTIVE'), ('Not Working', 'NOT WORKING'), ('Disposed', 'DISPOSED')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Remove',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('removed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(max_length=200)),
                ('iid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='its.Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('position', models.CharField(choices=[('SCT', 'Senior Computer Technician'), ('CT', 'Computer Technician'), ('SNA', 'Systems Network Administrator'), ('SPO', 'Senior Project Officer'), ('DPM', 'Deputy Programme Manager'), ('PM', 'Programme Manager')], max_length=3)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('to', models.CharField(max_length=120)),
                ('transfered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('iid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='its.Inventory')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='its.Staff')),
            ],
        ),
        migrations.AddField(
            model_name='remove',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='its.Staff'),
        ),
        migrations.AddField(
            model_name='dispose',
            name='iid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='its.Inventory'),
        ),
        migrations.AddField(
            model_name='dispose',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='its.Staff'),
        ),
        migrations.AddField(
            model_name='add',
            name='iid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='its.Inventory'),
        ),
        migrations.AddField(
            model_name='add',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='its.Staff'),
        ),
    ]
