# Generated by Django 2.0.8 on 2018-08-29 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('iid', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, max_length=20, null=True)),
                ('device_type', models.CharField(max_length=20)),
                ('serial_number', models.CharField(max_length=30, unique=True)),
                ('asset_code', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('position', models.CharField(choices=[('SCT', 'Senior Computer Technician'), ('CT', 'Computer Technician'), ('SNA', 'Systems Network Administrator'), ('SPO', 'Senior Project Officer'), ('DPM', 'Deputy Programme Manager'), ('PM', 'Programme Manager')], max_length=3)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('operation', models.CharField(choices=[('Add', 'ADD'), ('Transfer', 'TRANSFER'), ('Remove', 'REMOVE'), ('Change Status', 'CHANGE STATUS'), ('Disposed', 'DISPOSED'), ('Edit', 'EDIT')], max_length=14)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=120)),
                ('proprietor', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Active', 'ACTIVE'), ('Inactive', 'INACTIVE'), ('Not Working', 'NOT WORKING'), ('Disposed', 'DISPOSED')], max_length=12)),
                ('iid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='its.Inventory')),
                ('sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='its.Staff')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='manufacture_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='its.Mname'),
        ),
    ]
