# Generated by Django 2.0.8 on 2018-08-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0002_inventory_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='model_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
