# Generated by Django 2.0.8 on 2018-08-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0003_auto_20180808_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='model_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
