# Generated by Django 2.0.8 on 2018-08-15 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0004_auto_20180808_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='sid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='its.Staff'),
        ),
        migrations.AlterField(
            model_name='dispose',
            name='sid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='its.Staff'),
        ),
        migrations.AlterField(
            model_name='remove',
            name='iid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='its.Inventory'),
        ),
        migrations.AlterField(
            model_name='remove',
            name='sid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='its.Staff'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='its.Staff'),
        ),
    ]
