# Generated by Django 2.0.8 on 2018-08-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0006_auto_20180816_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
