# Generated by Django 2.0.8 on 2018-08-16 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0007_auto_20180816_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
