# Generated by Django 2.0.8 on 2018-08-17 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0008_auto_20180816_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='iid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='its.Inventory'),
        ),
    ]
