# Generated by Django 2.0.8 on 2018-08-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0012_auto_20180820_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='operation',
            field=models.CharField(choices=[('Add', 'ADD'), ('Transfer', 'TRANSFER'), ('Remove', 'REMOVE'), ('Change Status', 'CHANGE STATUS'), ('Disposed', 'DISPOSED')], max_length=14),
        ),
    ]
