# Generated by Django 2.0.8 on 2018-08-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0013_auto_20180820_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ['-date']},
        ),
    ]
