# Generated by Django 2.0.8 on 2018-08-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0014_auto_20180821_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={},
        ),
    ]
